	BIND(INS_NOP, NOP);
	BIND(INS_MOVE, MOVE);
	BIND(INS_ADD, ADD);	
	BIND(INS_ADDI, ADD);
	BIND(INS_ADDU, ADDU);
	BIND(INS_ADDIU, ADDU);	
	BIND(INS_SUB, SUB);
	BIND(INS_SUBU, SUBU);
	BIND(INS_SUBIU, SUBU);
	BIND(INS_MULT, MULT);
	BIND(INS_MULTU, MULTU);
	BIND(INS_DIV, DIV);
	BIND(INS_DIVU, DIVU);

	BIND(INS_NEGU, NEGU);
	BIND(INS_NEG, NEG);

	BIND(INS_LW, LW);
	BIND(INS_LH, LH);
	BIND(INS_LHU, LHU);
	BIND(INS_LB, LB);
	BIND(INS_LBU, LBU);
	BIND(INS_SW, SW);
	BIND(INS_SH, SH);
	BIND(INS_SB, SB);

	BIND(INS_LWL, LWL);
	BIND(INS_LWR, LWR);
	BIND(INS_SWL, SWL);
	BIND(INS_SWR, SWR);

	BIND(INS_LUI, LUI);
	BIND(INS_MFHI, MFHI);
	BIND(INS_MFLO, MFLO);

	BIND(INS_AND, AND);
	BIND(INS_ANDI, AND);
	BIND(INS_OR, OR);
	BIND(INS_ORI, OR);
	BIND(INS_XOR, XOR);
	BIND(INS_XORI, XOR);
	BIND(INS_NOR, NOR);
	BIND(INS_NORI, NOR);
	BIND(INS_SLT, SLT);
	BIND(INS_SLTI, SLT);
	BIND(INS_SLTU, SLTU);
	BIND(INS_SLTIU, SLTU);

	BIND(INS_SLL, SLL);
	BIND(INS_SLLV, SLL);
	BIND(INS_SRL, SRL);
	BIND(INS_SRLV, SRL);
	BIND(INS_SRA, SRA);
	BIND(INS_SRAV, SRA);

	BIND(INS_BEQ, BEQ);
	BIND(INS_BNE, BNE);
	BIND(INS_BEQZ, BEQZ);
	BIND(INS_BNEZ, BNEZ);
	BIND(INS_BLEZ, BLEZ);
	BIND(INS_BLTZ, BLTZ);
	BIND(INS_BGEZ, BGEZ);
	BIND(INS_BGTZ, BGTZ);
	BIND(INS_B, J);
	BIND(INS_BAL, JAL);

	BIND(INS_BC1T, BC1T);
	BIND(INS_BC1F, BC1F);

	BIND(INS_J, J);
	BIND(INS_JR, J);
	BIND(INS_JALR, JAL);
	BIND(INS_JAL, JAL);



	BIND(INS_MTC1, MTC1);
	BIND(INS_LWC1, LWC1);
	BIND(INS_LDC1, LDC1);
	BIND(INS_SWC1, SWC1);
	BIND(INS_SDC1, SDC1);


	BIND(INS_CVT_D_W, CVT_D_W);
	BIND(INS_CVT_D_S, CVT_D_S);
	BIND(INS_CVT_S_D, CVT_S_D);


	BIND(INS_DIV_S, DIV_S);
	BIND(INS_DIV_D, DIV_D);

	BIND(INS_C_LE_S, C_LE_S);

	BIND(INS_TEQ, TEQ);
	BIND(INS_TEQI, TEQ);
	BIND(INS_TGE, TGE);
	BIND(INS_TGEI, TGE);
	BIND(INS_TGEIU, TGEU);
	BIND(INS_TGEU, TGEU);
	BIND(INS_TLT, TLT);
	BIND(INS_TLTI, TLT);
	BIND(INS_TLTIU, TLTU);
	BIND(INS_TLTU, TLTU);
	BIND(INS_TNE, TNE);
	BIND(INS_TNEI, TNE);
